# Generated by Django 4.1.11 on 2023-09-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255, null=True)),
                ('field_name', models.CharField(max_length=255, null=True)),
                ('field_content', models.TextField(null=True)),
            ],
        ),
    ]
